version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 30
    lll:
      line-length: 170
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Using the variable on range scope `tc` in function literal
      - path: (.+)\.go$
        text: 'unused-parameter: parameter'
      - linters:
          - revive
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
      - linters:
          - revive
        text: 'var-naming: avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
