# Copyright 2023 The Flux Authors.
# SPDX-License-Identifier: Apache-2.0

name: test

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      -
        name: Test
        run: |
          make tidy
          make test
